"""empty message

Revision ID: 2aed419a2d39
Revises: f6d7bdbf02aa
Create Date: 2026-05-08 15:02:11.358253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2aed419a2d39'
down_revision: Union[str, Sequence[str], None] = 'f6d7bdbf02aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', name='role'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('user', 'assistant', name='role'),
               existing_nullable=True)
    # ### end Alembic commands ###
