"""add_dominator_fields

Revision ID: 8a9c42cab16f
Revises: 
Create Date: 2026-08-05 02:06:25.765381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9c42cab16f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('bot_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('message_count_dominator', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('users', 'messages_count_trial_dominator',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'subscription_status_dominator',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('none', 'trial', 'active', 'grace_period', 'cancelled', 'expired', name='subsstatus'),
               nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('users', 'subscription_tier_dominator',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('basic', 'deep', name='substier'),
               existing_nullable=True)
    op.alter_column('users', 'grace_period_attempts_dominator',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'free_messages_limit_for_dominant',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('33'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'free_messages_limit_for_dominant',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('33'))
    op.alter_column('users', 'grace_period_attempts_dominator',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'subscription_tier_dominator',
               existing_type=sa.Enum('basic', 'deep', name='substier'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'subscription_status_dominator',
               existing_type=sa.Enum('none', 'trial', 'active', 'grace_period', 'cancelled', 'expired', name='subsstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('users', 'messages_count_trial_dominator',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('users', 'message_count_dominator')
    op.drop_column('payments', 'bot_name')
    # ### end Alembic commands ###
