"""empty message

Revision ID: f6d7bdbf02aa
Revises: a9ef40dbe7bb
Create Date: 2026-05-08 14:53:13.459437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6d7bdbf02aa'
down_revision: Union[str, Sequence[str], None] = 'a9ef40dbe7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', name='role'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', name='role'),
               nullable=False)
    # ### end Alembic commands ###
